### ISSUE TITLE
A Metar remark with a certain SLP causes an exception

### ISSUE THREAD

**Issue by simno** [mivek/MetarParser#146]
**Describe the bug**
If you parse a metar string with a remark that contains a certain SLP, then it causes an exception

**To Reproduce**
Parse the following metar string:
```
METAR UTN 271900Z 11003KT 020V170 30SM FEW040 OVC130 14/03 A2979 RMK CF1AC8 CF TR SLP091 DENSITY ALT 200FT
```

**Expected behavior**
sea level preasure: 1009.1 hPa

**Exception**
```
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key CloudQuantity.SLP
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at io.github.mivek.internationalization.Messages.getString(Messages.java:47)
	at io.github.mivek.parser.RemarkParser.parse(RemarkParser.java:178)
	at io.github.mivek.parser.AbstractParser.parseRMK(AbstractParser.java:364)
	at io.github.mivek.parser.MetarParser.parse(MetarParser.java:93)
	at io.github.mivek.parser.MetarParser.parse(MetarParser.java:27)
	at io.github.mivek.facade.MetarFacade.decode(MetarFacade.java:36)

```

**Comment by mivek** [comment]
Hello @simno 
I found the cause of the bug, `TR SLP091` is recognized as a remark for an obscuration because
TR SLP091 matches the regex for the obscuration (2 letters, 1 space, 3 letters and 3 numbers).

I will push a fix as soon as possible.
